### ISSUE TITLE
Google logo missing

### ISSUE THREAD

**Issue by sguermond** [rails-girls-summer-of-code/RGSoC_slides#4]
The Google logo is not loading inside the images folder and appears to be gone from the website's [donation page](http://railsgirlssummerofcode.org/campaign/).

**Comment by alicetragedy** [comment]
@sguermond I am still investigating this. It might be a browser or, as you already said, an ad-blocker issue. Can you give me more info about the browser you are using? thank you!

**Comment by alicetragedy** [comment]
since we don't have any more details on this, I'm going to go ahead and close it. (note: looks fine [on the 2015 page](http://2015.railsgirlssummerofcode.org/campaign/) and in the `img` folder for 2015)
